# Generated by Django 2.1.3 on 2018-11-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblibrary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='surmane',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
