# Generated by Django 2.1.3 on 2018-11-07 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblibrary', '0002_author_surmane'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='surmane',
            new_name='surname',
        ),
    ]
